// <auto-generated />
using System;
using AIRWIZZ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIRWIZZ.Migrations
{
    [DbContext(typeof(AirwizzContext))]
    [Migration("20241120192626_FifthMg")]
    partial class FifthMg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIRWIZZ.Data.Entities.Arrival", b =>
                {
                    b.Property<int>("Arrival_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Arrival_Id"));

                    b.Property<string>("ArrivalCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.HasKey("Arrival_Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Arrivals");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.Booking", b =>
                {
                    b.Property<int>("Booking_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Booking_Id"));

                    b.Property<int>("ArrivalId")
                        .HasColumnType("int");

                    b.Property<int>("Book_Status_Result")
                        .HasColumnType("int");

                    b.Property<DateTime>("Booking_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartureId")
                        .HasColumnType("int");

                    b.Property<int>("Flight_Id")
                        .HasColumnType("int");

                    b.Property<int>("Passenger_Id")
                        .HasColumnType("int");

                    b.Property<int>("Seat_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Booking_Id");

                    b.HasIndex("ArrivalId");

                    b.HasIndex("DepartureId");

                    b.HasIndex("Flight_Id");

                    b.HasIndex("Passenger_Id");

                    b.HasIndex("Seat_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.CurrencyConversion", b =>
                {
                    b.Property<int>("Currency_Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Currency_Code"));

                    b.Property<float>("ConversionRate")
                        .HasColumnType("real");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("Currency_Code");

                    b.ToTable("CurrencyConversions");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.Departure", b =>
                {
                    b.Property<int>("Departure_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Departure_id"));

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Departure_id");

                    b.HasIndex("FlightId");

                    b.ToTable("Departures");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.Flight", b =>
                {
                    b.Property<int>("Flight_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Flight_Id"));

                    b.Property<string>("Airline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightNumber")
                        .HasColumnType("int");

                    b.Property<float>("TotalPrice")
                        .HasColumnType("real");

                    b.HasKey("Flight_Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.Passenger", b =>
                {
                    b.Property<int>("Passenger_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Passenger_Id"));

                    b.Property<DateOnly>("Date_Of_Birth")
                        .HasColumnType("date");

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport_Number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Passenger_Id");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.Payment", b =>
                {
                    b.Property<int>("Payment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Payment_Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodType")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Payment_Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.SeatPlan", b =>
                {
                    b.Property<int>("Seat_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Seat_Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("SeatClassType")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("Seat_Id");

                    b.HasIndex("FlightId");

                    b.ToTable("SeatPlans");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<DateTime?>("Date_joined")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_role")
                        .HasColumnType("int");

                    b.Property<int>("currency_preference")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.Arrival", b =>
                {
                    b.HasOne("AIRWIZZ.Data.Entities.Flight", "Flight")
                        .WithMany("Arrivals")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.Booking", b =>
                {
                    b.HasOne("AIRWIZZ.Data.Entities.Arrival", "Arrival")
                        .WithMany("Bookings")
                        .HasForeignKey("ArrivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIRWIZZ.Data.Entities.Departure", "Departure")
                        .WithMany("Bookings")
                        .HasForeignKey("DepartureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIRWIZZ.Data.Entities.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("Flight_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIRWIZZ.Data.Entities.Passenger", "Passenger")
                        .WithMany("Passenger_Bookings")
                        .HasForeignKey("Passenger_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIRWIZZ.Data.Entities.SeatPlan", "SeatPlan")
                        .WithMany("Bookings")
                        .HasForeignKey("Seat_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIRWIZZ.Data.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arrival");

                    b.Navigation("Departure");

                    b.Navigation("Flight");

                    b.Navigation("Passenger");

                    b.Navigation("SeatPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.Departure", b =>
                {
                    b.HasOne("AIRWIZZ.Data.Entities.Flight", "Flight")
                        .WithMany("Departures")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.Payment", b =>
                {
                    b.HasOne("AIRWIZZ.Data.Entities.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("AIRWIZZ.Data.Entities.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIRWIZZ.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.SeatPlan", b =>
                {
                    b.HasOne("AIRWIZZ.Data.Entities.Flight", "Flight")
                        .WithMany("SeatPlans")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.Arrival", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.Booking", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.Departure", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.Flight", b =>
                {
                    b.Navigation("Arrivals");

                    b.Navigation("Bookings");

                    b.Navigation("Departures");

                    b.Navigation("SeatPlans");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.Passenger", b =>
                {
                    b.Navigation("Passenger_Bookings");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.SeatPlan", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("AIRWIZZ.Data.Entities.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
